In [9]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [ ]:
(11,Agent,Lion,2020-09-15,2020-12-07),
(12,Agent,Lion,2020-09-15,2021-02-06),
(13,Agent,Lion,2020-09-17,2021-01-20),
(14,IFA,Apple,2020-09-17,2021-01-26),
(15,Developer,Leaf,2020-09-17,2020-12-07),
(16,Agent,Lion,2020-09-17,2020-12-07),
(17,IFA,Apple,2020-09-21,2020-12-08),
(18,Agent,Potato,2020-09-21,2021-01-14),
(19,Agent,Lion,2020-09-22,2020-12-07),
(20,Agent,Potato,2020-09-22,2021-01-04)
(21,Other,0,2020-09-24,2020-09-24),
(22,Other,0,2020-09-24,2020-09-24),
(23,Other,0,2020-09-24,2020-09-24),
(24,Other,0,2020-09-24,2020-09-24),
(25,Agent,Potato,2020-09-29,2020-12-04),
(26,Agent,Leaf,2020-09-29,2021-01-12),
(27,Agent,Potato,2020-10-01,2020-12-04),
(28,Agent,Potato,2020-10-01,2021-01-04),
(29,Agent,Apple,2020-10-01,2021-01-26),
(30,Other,Apple,2020-10-01,2021-01-26),
(31,IFA,Apple,2020-10-01,2021-01-26);

In [ ]:
40,Agent,Apple,2020-10-19,2021-01-04
41,Agent,Leaf,2020-10-21,2020-12-04
42,Developer,Apple,2020-10-22,2021-01-26
43,Agent,Lion,2020-10-26,2020-12-07
44,Agent,Leaf,2020-10-26,2020-12-04
45,Other,Potato,2020-10-29,2020-12-04
46,Developer,Apple,2020-10-29,2021-01-26
47,Agent,Lion,2020-10-29,2020-12-07
48,Agent,Lion,2020-10-29,2020-12-07
49,Agent,Lion,2020-10-29,2020-12-07
50,Agent,Daisy,2020-10-29,2020-12-03
51,Agent,Daisy,2020-10-29,2020-12-08
52,Agent,Daisy,2020-10-29,2020-12-08
53,Agent,Potato,2020-11-02,2021-01-26
54,Agent,Lion,2020-11-03,2020-12-07
55,Lender,Daisy,2020-11-10,2020-12-08
56,Developer,Lion,2020-11-12,2020-12-07
57,Agent,Lion,2020-11-13,2020-12-07
58,Agent,Lion,2020-11-13,2020-12-07
59,IFA,Lion,2020-11-15,2020-12-07
60,Agent,Leaf,2020-11-17,2021-04-01
61,Developer,Lion,2020-11-18,2020-12-07
62,Agent,Leaf,2020-11-18,2020-12-04
63,Lender,Apple,2020-11-20,2021-02-10
64,Agent,Lion,2020-11-20,2021-01-04
65,Agent,Leaf,2020-11-20,2020-12-04
66,Agent,Lion,2020-11-21,2020-12-07
67,IFA,Potato,2020-11-21,2021-05-05
68,Developer,Daisy,2020-11-21,2020-12-08
69,Agent,Apple,2020-11-22,2021-02-10
70,Agent,Potato,2020-11-23,2020-12-04
71,Agent,Lion,2020-11-23,2020-12-07
72,Agent,Lion,2020-11-23,2020-12-07
73,IFA,Potato,2020-11-23,2021-02-10
74,Agent,Lion,2020-11-23,2021-02-23
75,Agent,Apple,2020-11-23,2021-02-10
76,Agent,Root,2020-11-23,2021-02-08
77,Agent,Potato,2020-11-23,2020-12-04
78,Agent,Potato,2020-11-23,2020-12-04
79,Agent,Potato,2020-11-23,2020-12-04
80,Agent,Daisy,2020-11-23,2020-12-08
81,Agent,Apple,2020-11-23,2021-01-28
82,Developer,Apple,2020-11-23,2021-02-10
83,Agent,Lion,2020-11-24,2020-12-07
84,IFA,0,2020-11-24,2020-11-24
85,Agent,Potato,2020-11-24,2020-12-04
86,Developer,Potato,2020-11-24,2021-01-05
87,Management company,Potato,2020-11-24,2021-01-05
88,Agent,Potato,2020-11-24,2021-01-04
89,Management company,Lion,2020-11-24,2020-12-04
90,Management company,Potato,2020-11-24,2020-12-04
91,Agent,Potato,2020-11-24,2021-04-15
92,Agent,Root,2020-11-24,2021-04-19
93,Agent,Potato,2020-11-24,2021-02-10
94,Agent,Root,2020-11-24,2021-02-03
95,Agent,Tree,2020-11-25,2021-02-04
96,Other,Leaf,2020-12-01,2020-12-04
97,Other,Leaf,2020-12-01,2020-12-04
98,IFA,Daisy,2020-12-02,2020-12-11
99,Developer,Potato,2020-12-03,2021-03-04
100,Agent,Lion,2020-12-04,2020-12-04
101,Other,Leaf,2020-12-04,2020-12-04
102,Agent,Leaf,2020-12-04,2020-12-04
103,Agent,Tree,2020-12-07,2020-12-07
104,Agent,Potato,2020-12-07,2020-12-11
105,IFA,Potato,2020-12-07,2020-12-07
106,Agent,Lion,2020-12-07,2020-12-07
107,Agent,Leaf,2020-12-07,2020-12-07
108,Agent,Leaf,2020-12-07,2020-12-07
109,Agent,Leaf,2020-12-07,2020-12-07
111,Agent,Tree,2020-12-08,2020-12-08
112,Agent,Potato,2020-12-08,2020-12-08
113,Other,Daisy,2020-12-08,2020-12-08
114,Agent,Daisy,2020-12-08,2020-12-08
115,Agent,Daisy,2020-12-08,2020-12-08
116,Other,Daisy,2020-12-08,2020-12-08
117,Agent,Daisy,2020-12-08,2020-12-08
118,Agent,Lion,2020-12-09,2020-12-09
119,Agent,Potato,2020-12-09,2020-12-09
120,Agent,Tree,2020-12-09,2020-12-09
121,Agent,Potato,2020-12-10,2020-12-10
122,Management company,Tree,2020-12-10,2020-12-10
123,Agent,Root,2020-12-10,2021-02-09
124,Agent,Root,2020-12-10,2021-04-20
125,Agent,Sky,2020-12-10,2021-04-27
126,Agent,Root,2020-12-10,2021-04-20
127,Agent,Apple,2020-12-12,2020-12-12
128,Agent,Daisy,2020-12-15,2020-12-15
129,IFA,Daisy,2020-12-15,2020-12-15
130,Lender,Tree,2020-12-16,2020-12-16
131,Management company,Root,2020-12-16,2021-04-20
132,Agent,Lion,2020-12-17,2020-12-17
133,Agent,Root,2020-12-18,2021-04-20
134,Agent,Tree,2020-12-21,2020-12-21
135,Agent,Apple,2020-12-22,2020-12-22
136,Agent,Potato,2020-12-22,2020-12-22
137,Agent,Lion,2021-01-04,2021-01-04
138,Agent,Lion,2021-01-04,2021-01-19
139,Developer,Root,2021-01-04,2021-04-20
140,Agent,Potato,2021-01-05,2021-01-05
141,Agent,Tulip,2021-01-05,2021-01-18
142,Agent,Potato,2021-01-06,2021-01-06
143,Agent,Potato,2021-01-06,2021-01-06
144,Agent,Potato,2021-01-06,2021-01-06
145,Agent,Potato,2021-01-06,2021-01-06
146,Developer,Daisy,2021-01-06,2021-01-18
147,IFA,Leaf,2021-01-06,2021-01-06
148,Agent,Lion,2021-01-07,2021-01-07
149,Management company,Potato,2021-01-07,2021-01-07
150,Developer,Apple,2021-01-07,2021-01-07
151,Developer,Potato,2021-01-07,2021-01-07
152,Agent,Sky,2021-01-08,2021-05-03
153,Developer,Potato,2021-01-08,2021-01-08
154,Lender,Potato,2021-01-08,2021-01-08
155,IFA,Potato,2021-01-08,2021-04-16
156,Agent,Root,2021-01-11,2021-04-20
157,Agent,Apple,2021-01-11,2021-01-11
158,Agent,Potato,2021-01-11,2021-01-11
159,Agent,Potato,2021-01-11,2021-01-11
160,Agent,Potato,2021-01-11,2021-01-11
161,Agent,Potato,2021-01-11,2021-02-19
162,Agent,Daisy,2021-01-11,2021-01-11
163,Agent,Apple,2021-01-12,2021-01-12
164,Other,Apple,2021-01-12,2021-01-12
165,Agent,Potato,2021-01-12,2021-01-12
166,IFA,Tree,2021-01-13,2021-01-13
167,Developer,Potato,2021-01-13,2021-01-13
168,Developer,Apple,2021-01-13,2021-01-13
169,Agent,Daisy,2021-01-13,2021-02-09
170,Agent,Potato,2021-01-14,2021-01-14
171,IFA,Leaf,2021-01-14,2021-01-14
172,Agent,Lion,2021-01-14,2021-01-14
173,IFA,Daisy,2021-01-15,2021-01-15
174,Other,Tree,2021-01-15,2021-01-15
175,Developer,Tree,2021-01-18,2021-01-18
176,Developer,Tree,2021-01-18,2021-01-18
177,Other,Apple,2021-01-18,2021-01-18
178,Agent,Apple,2021-01-18,2021-01-18
179,Agent,Root,2021-01-19,2021-01-19
180,Agent,Root,2021-01-19,2021-01-19
181,Agent,Root,2021-01-19,2021-01-19
182,Agent,Root,2021-01-19,2021-01-19
183,Agent,Root,2021-01-19,2021-01-19
184,Agent,Root,2021-01-19,2021-01-19
185,Agent,Root,2021-01-19,2021-01-19
186,IFA,Apple,2021-01-20,2021-01-20
187,Agent,Root,2021-01-20,2021-01-20
188,Agent,Root,2021-01-20,2021-01-20
189,Developer,Root,2021-01-20,2021-01-20
190,Agent,Root,2021-01-20,2021-01-20
191,Insurer,Tulip,2021-01-20,2021-01-20
192,Agent,Tree,2021-01-21,2021-01-21
193,Agent,Root,2021-01-21,2021-01-21
194,Agent,Root,2021-01-21,2021-01-21
195,Agent,Root,2021-01-21,2021-01-21
196,Agent,Root,2021-01-21,2021-01-21
197,Agent,Daisy,2021-01-22,2021-02-01
198,Agent,Daisy,2021-01-22,2021-01-22
199,Agent,Potato,2021-01-22,2021-02-26
200,Agent,Daisy,2021-01-22,2021-01-22
201,Other,Tulip,2021-01-23,2021-01-23
202,Developer,Apple,2021-01-23,2021-01-23
203,Agent,Apple,2021-01-23,2021-01-23
204,Developer,Apple,2021-01-23,2021-01-23
205,Other,Apple,2021-01-23,2021-01-23
206,Developer,Potato,2021-01-25,2021-01-25
207,Agent,Root,2021-01-25,2021-01-25
208,Agent,Lion,2021-01-25,2021-01-25
209,Agent,Root,2021-01-25,2021-01-25
210,Agent,Root,2021-01-25,2021-01-25
211,Agent,Root,2021-01-25,2021-01-25
212,Agent,Daisy,2021-01-25,2021-01-25
213,Lender,Daisy,2021-01-25,2021-01-26
214,Agent,Daisy,2021-01-25,2021-01-25
215,IFA,Daisy,2021-01-25,2021-01-25
216,IFA,Daisy,2021-01-25,2021-01-25
217,Agent,Daisy,2021-01-25,2021-01-25
218,Other,Daisy,2021-01-26,2021-01-26
219,Agent,Root,2021-01-26,2021-01-26
220,Other,Root,2021-01-26,2021-01-26
221,Agent,Root,2021-01-26,2021-01-26
222,Agent,Root,2021-01-26,2021-01-26
223,Agent,Root,2021-01-26,2021-01-26
224,Agent,Sky,2021-01-26,2021-04-30
225,Agent,Apple,2021-01-27,2021-01-27
226,Agent,Root,2021-01-27,2021-04-20
227,Agent,Root,2021-01-27,2021-02-23
228,Agent,Root,2021-01-27,2021-01-27
229,Insurer,Root,2021-01-27,2021-01-27
230,Agent,Leaf,2021-01-28,2021-01-28
231,IFA,Leaf,2021-01-29,2021-01-29
232,Agent,Potato,2021-02-01,2021-02-01
233,Other,Apple,2021-02-01,2021-02-01
234,Agent,Potato,2021-02-01,2021-02-01
235,Other,Potato,2021-02-01,2021-02-01
236,Agent,Root,2021-02-01,2021-02-01
237,Agent,Root,2021-02-01,2021-02-01
238,Agent,Root,2021-02-02,2021-04-20
239,Agent,Tree,2021-02-02,2021-02-02
240,Agent,Daisy,2021-02-02,2021-02-02
241,Agent,Root,2021-02-03,2021-04-08
242,Agent,Root,2021-02-03,2021-02-03
243,Agent,Tree,2021-02-04,2021-02-04
244,Agent,Potato,2021-02-04,2021-02-04
245,Agent,Potato,2021-02-04,2021-03-01
246,Other,Potato,2021-02-04,2021-02-04
247,Agent,Potato,2021-02-04,2021-02-04
248,Agent,Potato,2021-02-04,2021-02-04
249,Agent,Potato,2021-02-04,2021-02-04
250,Agent,Potato,2021-02-04,2021-02-04
251,Agent,Tree,2021-02-05,2021-02-05
252,Agent,Root,2021-02-05,2021-04-08
253,Agent,Lion,2021-02-06,2021-02-06
254,Lender,Daisy,2021-02-07,2021-02-07
255,Agent,Root,2021-02-08,2021-04-08
256,Agent,Potato,2021-02-08,2021-02-08
257,Agent,Potato,2021-02-08,2021-02-08
258,Agent,Potato,2021-02-08,2021-02-08
259,Agent,Potato,2021-02-08,2021-02-08
260,Agent,Potato,2021-02-08,2021-02-08
261,Agent,Potato,2021-02-08,2021-02-08
262,Agent,Root,2021-02-09,2021-02-09
263,Agent,Leaf,2021-02-09,2021-04-21
264,Agent,Root,2021-02-09,2021-02-09
265,Agent,Root,2021-02-09,2021-02-09
266,Agent,Root,2021-02-09,2021-02-09
267,Agent,Root,2021-02-09,2021-02-09
268,Agent,Root,2021-02-09,2021-02-09
269,Agent,Root,2021-02-09,2021-02-09
270,Agent,Root,2021-02-09,2021-02-09
271,Agent,Root,2021-02-09,2021-02-09
272,Agent,Root,2021-02-09,2021-04-30
273,Agent,Root,2021-02-09,2021-02-09
274,Agent,Root,2021-02-09,2021-02-09
275,Agent,Root,2021-02-09,2021-02-09
276,Agent,Root,2021-02-09,2021-02-09
277,Agent,Root,2021-02-09,2021-02-09
278,Agent,Root,2021-02-09,2021-02-09
279,Agent,Root,2021-02-09,2021-02-09
280,Agent,Root,2021-02-09,2021-02-09
281,Agent,Root,2021-02-09,2021-02-09
282,IFA,Root,2021-02-09,2021-02-09
283,Agent,Root,2021-02-09,2021-02-09
284,Agent,Root,2021-02-09,2021-02-09
285,Agent,Leaf,2021-02-09,2021-02-09
286,Other,Tree,2021-02-10,2021-02-10
287,Agent,Tree,2021-02-10,2021-02-10
288,Developer,Tree,2021-02-10,2021-02-10
289,IFA,Tree,2021-02-10,2021-02-10
290,Other,Tulip,2021-02-10,2021-02-10
291,Agent,Potato,2021-02-15,2021-02-15
292,Other,Potato,2021-02-15,2021-02-15
293,Agent,Potato,2021-02-15,2021-02-15
294,Agent,Potato,2021-02-16,2021-02-16
295,Agent,Potato,2021-02-16,2021-02-16
296,Agent,Daisy,2021-02-16,2021-04-19
297,Management company,Tree,2021-02-16,2021-02-16
298,Other,Potato,2021-02-16,2021-02-16
299,Agent,Apple,2021-02-16,2021-02-16
300,Management company,Tree,2021-02-16,2021-02-16
301,Agent,Potato,2021-02-17,2021-02-17
302,Lender,Tulip,2021-02-17,2021-02-17
303,Agent,Daisy,2021-02-18,2021-02-18
304,Agent,Daisy,2021-02-18,2021-02-18
305,Agent,Root,2021-02-18,2021-02-18
306,Agent,Sky,2021-02-18,2021-04-30
307,Agent,Lion,2021-02-18,2021-02-23
308,Agent,Root,2021-02-18,2021-02-18
309,Management company,Tree,2021-02-19,2021-02-19
310,Agent,Potato,2021-02-19,2021-02-19
311,Agent,Root,2021-02-19,2021-02-19
312,Agent,Potato,2021-02-19,2021-02-19
313,Agent,Root,2021-02-19,2021-03-26
314,Agent,Root,2021-02-19,2021-02-19
315,Agent,Daisy,2021-02-19,2021-02-19
316,Agent,Daisy,2021-02-19,2021-02-19
317,Agent,Leaf,2021-02-19,2021-02-19
318,Agent,Apple,2021-02-20,2021-02-20
319,Agent,Potato,2021-02-22,2021-02-22
320,Agent,Root,2021-02-23,2021-04-20
321,Agent,Potato,2021-02-23,2021-02-23
322,Agent,Lion,2021-02-23,2021-02-23
323,Agent,Lion,2021-02-23,2021-02-23
324,Agent,Root,2021-02-24,2021-02-24
325,Management company,Tree,2021-02-24,2021-02-24
326,Agent,Potato,2021-02-24,2021-02-24
327,Influencer,Daisy,2021-02-24,2021-02-24
328,Agent,Tree,2021-02-25,2021-02-25
329,Agent,Root,2021-02-25,2021-04-20
330,Agent,Root,2021-02-25,2021-02-25
331,Developer,Tree,2021-02-25,2021-02-25
332,Agent,Root,2021-02-25,2021-02-25
333,Agent,Root,2021-02-25,2021-02-25
334,Influencer,Leaf,2021-02-25,2021-02-25
335,Agent,Potato,2021-02-26,2021-02-26
336,Agent,Tree,2021-02-26,2021-02-26
337,Agent,Apple,2021-02-26,2021-02-26
338,Lender,Potato,2021-02-26,2021-02-26
339,Agent,Lion,2021-02-26,2021-02-26
340,Agent,Tree,2021-03-01,2021-03-01
341,Agent,Tree,2021-03-01,2021-03-01
342,Influencer,Apple,2021-03-01,2021-03-01
343,Influencer,Root,2021-03-02,2021-03-02
344,Lender,Root,2021-03-02,2021-03-02
345,Agent,Root,2021-03-02,2021-03-02
346,Influencer,Root,2021-03-03,2021-03-03
347,Agent,Root,2021-03-03,2021-04-20
348,IFA,Tree,2021-03-03,2021-03-03
349,IFA,Potato,2021-03-04,2021-03-04
350,Agent,Leaf,2021-03-04,2021-03-04
351,Management company,Daisy,2021-03-04,2021-03-04
352,Agent,Lion,2021-03-07,2021-03-07
353,Agent,Tree,2021-03-08,2021-03-08
354,Developer,Tree,2021-03-08,2021-03-08
355,Agent,Root,2021-03-08,2021-04-08
356,Influencer,Root,2021-03-08,2021-03-08
357,Agent,Apple,2021-03-08,2021-03-08
358,Influencer,Tree,2021-03-09,2021-03-09
359,Developer,Tree,2021-03-09,2021-03-09
360,Influencer,Root,2021-03-09,2021-03-09
361,Agent,Root,2021-03-09,2021-03-09
362,Agent,Apple,2021-03-10,2021-04-29
363,Influencer,Daisy,2021-03-10,2021-03-10
364,Agent,Potato,2021-03-11,2021-03-11
365,Agent,Root,2021-03-12,2021-04-20
366,Influencer,Root,2021-03-12,2021-04-08
367,Agent,Potato,2021-03-13,2021-04-26
368,Agent,Tree,2021-03-16,2021-03-16
369,Agent,Potato,2021-03-16,2021-03-20
370,Influencer,Tree,2021-03-17,2021-03-17
371,IFA,Tree,2021-03-18,2021-03-18
372,Agent,Potato,2021-03-18,2021-03-18
373,Lender,Potato,2021-03-19,2021-04-15
374,IFA,Apple,2021-03-22,2021-03-22
375,Agent,Daisy,2021-03-23,2021-03-23
376,IFA,Leaf,2021-03-26,2021-03-26
377,Agent,Apple,2021-03-28,2021-03-28
378,Lender,Potato,2021-03-29,2021-03-29
379,IFA,Potato,2021-03-29,2021-03-29
380,Agent,Root,2021-03-30,2021-03-30
381,IFA,Potato,2021-03-31,2021-03-31
382,Agent,Potato,2021-04-01,2021-04-01
383,Agent,Daisy,2021-04-01,2021-04-01
384,Agent,Daisy,2021-04-01,2021-04-01
385,Agent,Apple,2021-04-05,2021-04-05
386,Developer,Apple,2021-04-05,2021-04-05
387,IFA,Apple,2021-04-06,2021-04-06
388,Agent,Daisy,2021-04-08,2021-04-08
389,Agent,Root,2021-04-08,2021-04-08
390,Agent,Root,2021-04-12,2021-04-12
391,Developer,Horiz,2021-04-12,2021-04-30
392,IFA,Horiz,2021-04-12,2021-04-27
393,IFA,Horiz,2021-04-12,2021-04-12
394,Agent,Leaf,2021-04-12,2021-04-12
395,IFA,Potato,2021-04-13,2021-04-13
396,Agent,Cloud,2021-04-13,2021-04-29
397,Influencer,Cloud,2021-04-13,2021-04-29
398,Agent,Cloud,2021-04-13,2021-04-26
399,Agent,Cloud,2021-04-13,2021-04-29
400,IFA,Horiz,2021-04-13,2021-04-13
401,Management company,Cloud,2021-04-13,2021-04-29
402,IFA,Horiz,2021-04-13,2021-04-13
403,Agent,Horiz,2021-04-13,2021-04-13
404,Management company,Cloud,2021-04-13,2021-04-29
405,Agent,Cloud,2021-04-13,2021-04-29
406,Agent,Cloud,2021-04-13,2021-04-29
407,Agent,Cloud,2021-04-13,2021-04-29
408,Management company,Cloud,2021-04-13,2021-04-29
409,IFA,Horiz,2021-04-13,2021-04-27
410,IFA,Horiz,2021-04-13,2021-04-13
411,IFA,Cloud,2021-04-13,2021-04-29
412,Agent,Horiz,2021-04-14,2021-04-27
413,Agent,Horiz,2021-04-14,2021-04-27
414,Agent,Horiz,2021-04-14,2021-04-14
415,Agent,Horiz,2021-04-14,2021-04-27
416,Agent,Horiz,2021-04-14,2021-04-14
417,IFA,Horiz,2021-04-14,2021-04-14
418,Agent,Horiz,2021-04-14,2021-04-14
419,Agent,Horiz,2021-04-14,2021-04-14
420,IFA,Potato,2021-04-16,2021-04-16
421,IFA,Potato,2021-04-16,2021-04-16
422,IFA,Cloud,2021-04-16,2021-04-26
423,Developer,Root,2021-04-17,2021-04-17
424,Agent,Fig,2021-04-19,2021-04-19
425,Influencer,Root,2021-04-20,2021-04-20
426,Lender,Root,2021-04-20,2021-04-23
427,Influencer,Potato,2021-04-20,2021-04-20
428,Influencer,Root,2021-04-20,2021-04-20
429,IFA,Root,2021-04-20,2021-04-20
430,IFA,Root,2021-04-20,2021-04-20
431,Agent,Root,2021-04-20,2021-04-20
432,IFA,Root,2021-04-20,2021-04-20
433,Influencer,Root,2021-04-20,2021-04-20
434,Insurer,Root,2021-04-20,2021-04-20
435,IFA,Root,2021-04-20,2021-04-20
436,IFA,Root,2021-04-20,2021-04-20
437,Influencer,Root,2021-04-20,2021-04-20
438,Agent,Root,2021-04-20,2021-04-20
439,Agent,Root,2021-04-20,2021-04-20
440,Influencer,Root,2021-04-20,2021-04-20
441,Agent,Root,2021-04-20,2021-04-20
442,Agent,Root,2021-04-20,2021-04-20
443,Agent,Root,2021-04-20,2021-04-20
444,Lender,Root,2021-04-20,2021-04-20
445,Influencer,Root,2021-04-20,2021-04-20
446,Agent,Root,2021-04-20,2021-04-20
447,Influencer,Root,2021-04-20,2021-04-20
448,Agent,Root,2021-04-20,2021-04-20
449,Agent,Root,2021-04-20,2021-04-20
450,Agent,Sky,2021-04-20,2021-04-23
451,Agent,Sky,2021-04-20,2021-04-23
452,Management company,Root,2021-04-21,2021-04-21
453,Lender,Potato,2021-04-21,2021-04-21
454,Agent,Potato,2021-04-21,2021-04-21
455,Agent,Cloud,2021-04-21,2021-04-29
456,Agent,Root,2021-04-22,2021-04-22
457,IFA,Leaf,2021-04-22,2021-04-22
458,Influencer,Leaf,2021-04-22,2021-04-22
459,Agent,Daisy,2021-04-22,2021-04-22
460,Agent,Potato,2021-04-23,2021-04-23
461,Lender,Root,2021-04-23,2021-04-23
462,Agent,Sky,2021-04-23,2021-04-23
463,Agent,Sky,2021-04-23,2021-04-23
464,Developer,Cloud,2021-04-23,2021-04-29
465,Agent,Cloud,2021-04-23,2021-04-29
466,Agent,Potato,2021-04-26,2021-04-26
467,Agent,Potato,2021-04-26,2021-04-26
468,Agent,Potato,2021-04-26,2021-04-26
469,Agent,Leaf,2021-04-26,2021-04-26
470,Lender,Horiz,2021-04-27,2021-04-30
471,Lender,Daisy,2021-04-27,2021-04-27
472,Agent,Potato,2021-04-28,2021-04-28
473,Agent,Leaf,2021-04-28,2021-04-28
474,Agent,Horiz,2021-04-28,2021-04-28
475,Management company,Potato,2021-04-29,2021-04-29
476,Agent,Potato,2021-04-29,2021-04-29
477,Management company,Cloud,2021-04-29,2021-04-29
478,Management company,Cloud,2021-04-29,2021-04-29
479,Agent,Cloud,2021-04-29,2021-04-29
480,Agent,Cloud,2021-04-29,2021-04-29
481,Agent,Potato,2021-04-30,2021-04-30
482,Agent,Sky,2021-04-30,2021-04-30
483,Agent,Sky,2021-04-30,2021-04-30
484,Agent,Sky,2021-04-30,2021-04-30
485,Agent,Lion,2021-04-30,2021-04-30
486,Agent,Lion,2021-04-30,2021-04-30
487,Agent,Sky,2021-04-30,2021-04-30
488,Influencer,Sky,2021-04-30,2021-04-30
489,Agent,Sky,2021-04-30,2021-04-30
490,Agent,Sky,2021-04-30,2021-04-30
491,Agent,Sky,2021-04-30,2021-04-30
492,IFA,Cloud,2021-04-30,2021-04-30
493,Agent,Sky,2021-05-03,2021-05-03
494,Agent,Sky,2021-05-03,2021-05-03
495,Agent,Sky,2021-05-03,2021-05-03
496,Agent,Sky,2021-05-03,2021-05-03
497,Agent,Sky,2021-05-03,2021-05-03
498,Agent,Sky,2021-05-03,2021-05-03
499,Agent,Sky,2021-05-03,2021-05-03
500,Agent,Sky,2021-05-03,2021-05-03
501,Agent,Sky,2021-05-03,2021-05-03
502,Agent,Sky,2021-05-03,2021-05-03
503,Agent,Sky,2021-05-03,2021-05-03
504,Agent,Sky,2021-05-03,2021-05-03
505,Agent,Sky,2021-05-03,2021-05-03
506,Agent,Sky,2021-05-03,2021-05-03
507,Agent,Sky,2021-05-03,2021-05-03
508,Agent,Sky,2021-05-03,2021-05-03
509,Agent,Leaf,2021-05-04,2021-05-04
510,Agent,Leaf,2021-05-04,2021-05-04
511,IFA,Leaf,2021-05-04,2021-05-04
512,Agent,Fig,2021-05-04,2021-05-04
513,Agent,Fig,2021-05-04,2021-05-04
514,Agent,Fig,2021-05-04,2021-05-04
515,Agent,Daisy,2021-05-04,2021-05-04
516,IFA,Potato,2021-05-05,2021-05-05
517,IFA,Potato,2021-05-05,2021-05-05
518,IFA,Potato,2021-05-05,2021-05-05
519,Agent,Lion,2021-05-05,2021-05-05
520,Influencer,Sky,2021-05-05,2021-05-05
521,Agent,Sky,2021-05-05,2021-05-05
522,Agent,Sky,2021-05-05,2021-05-05
523,Agent,Sky,2021-05-05,2021-05-05
524,Agent,Sky,2021-05-05,2021-05-05

In [10]:
partner= pd.read_csv ("partners.csv")

In [11]:
partner

      id    created_at    updated_at partner_type lead_sales_contact
0      2  1.598856e+18  1.607047e+18        Agent             Potato
1      3  1.598859e+18  1.618882e+18        Agent               Lion
2      4  1.598859e+18  1.616642e+18        Agent             Potato
3      5  1.598860e+18  1.607331e+18        Agent               Lion
4      6  1.598866e+18  1.609743e+18        Agent             Potato
..   ...           ...           ...          ...                ...
517  520  1.620188e+18  1.620188e+18   Influencer                Sky
518  521  1.620189e+18  1.620189e+18        Agent                Sky
519  522  1.620190e+18  1.620190e+18        Agent                Sky
520  523  1.620190e+18  1.620190e+18        Agent                Sky
521  524  1.620193e+18  1.620193e+18        Agent                Sky

[522 rows x 5 columns]

# converting from  Unix Nano format to Datetime

In [12]:
partner2= partner.astype({'created_at':'datetime64[ns]', 'updated_at': 'datetime64[ns]'})

In [13]:
partner2

,id,created_at,updated_at,partner_type,lead_sales_contact
0,2,2020-08-31 06:47:46.322480128,2020-12-04 01:51:12.823859968,Agent,Potato
1,3,2020-08-31 07:37:09.759830016,2021-04-20 01:31:02.989189888,Agent,Lion
2,4,2020-08-31 07:38:16.698880000,2021-03-25 03:10:56.065319936,Agent,Potato
3,5,2020-08-31 07:43:16.281430016,2020-12-07 08:43:01.086640128,Agent,Lion
4,6,2020-08-31 09:18:53.133669888,2021-01-04 06:51:57.822899968,Agent,Potato
...,...,...,...,...,...
517,520,2021-05-05 04:13:44.501060096,2021-05-05 04:13:44.501060096,Influencer,Sky
518,521,2021-05-05 04:29:34.667599872,2021-05-05 04:29:34.667599872,Agent,Sky
519,522,2021-05-05 04:40:44.832560128,2021-05-05 04:40:44.832560128,Agent,Sky
520,523,2021-05-05 04:53:35.962680064,2021-05-05 04:53:35.962680064,Agent,Sky
521,524,2021-05-05 05:43:12.316570112,2021-05-05 05:43:12.316570112,Agent,Sky

In [14]:
partner2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522 entries, 0 to 521
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  522 non-null    int64
 1   created_at          522 non-null    datetime64[ns]
 2   updated_at          522 non-null    datetime64[ns]
 3   partner_type        522 non-null    object
 4   lead_sales_contact  522 non-null    object
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 20.5+ KB

In [15]:
partner2["created_at"] = pd.to_datetime(partner2["created_at"])

In [16]:
partner2["updated_at"] = pd.to_datetime(partner2["updated_at"])

In [17]:
partner2["updated_at"]

0     2020-12-04 01:51:12.823859968
1     2021-04-20 01:31:02.989189888
2     2021-03-25 03:10:56.065319936
3     2020-12-07 08:43:01.086640128
4     2021-01-04 06:51:57.822899968
                   ...
517   2021-05-05 04:13:44.501060096
518   2021-05-05 04:29:34.667599872
519   2021-05-05 04:40:44.832560128
520   2021-05-05 04:53:35.962680064
521   2021-05-05 05:43:12.316570112
Name: updated_at, Length: 522, dtype: datetime64[ns]

In [18]:
partner2['created_date']= pd.DatetimeIndex(partner2.created_at).date
partner2['updated_date']= pd.DatetimeIndex(partner2.updated_at).date

In [19]:
partner2

,id,created_at,updated_at,partner_type,lead_sales_contact,created_date,updated_date
0,2,2020-08-31 06:47:46.322480128,2020-12-04 01:51:12.823859968,Agent,Potato,2020-08-31,2020-12-04
1,3,2020-08-31 07:37:09.759830016,2021-04-20 01:31:02.989189888,Agent,Lion,2020-08-31,2021-04-20
2,4,2020-08-31 07:38:16.698880000,2021-03-25 03:10:56.065319936,Agent,Potato,2020-08-31,2021-03-25
3,5,2020-08-31 07:43:16.281430016,2020-12-07 08:43:01.086640128,Agent,Lion,2020-08-31,2020-12-07
4,6,2020-08-31 09:18:53.133669888,2021-01-04 06:51:57.822899968,Agent,Potato,2020-08-31,2021-01-04
...,...,...,...,...,...,...,...
517,520,2021-05-05 04:13:44.501060096,2021-05-05 04:13:44.501060096,Influencer,Sky,2021-05-05,2021-05-05
518,521,2021-05-05 04:29:34.667599872,2021-05-05 04:29:34.667599872,Agent,Sky,2021-05-05,2021-05-05
519,522,2021-05-05 04:40:44.832560128,2021-05-05 04:40:44.832560128,Agent,Sky,2021-05-05,2021-05-05
520,523,2021-05-05 04:53:35.962680064,2021-05-05 04:53:35.962680064,Agent,Sky,2021-05-05,2021-05-05
521,524,2021-05-05 05:43:12.316570112,2021-05-05 05:43:12.316570112,Agent,Sky,2021-05-05,2021-05-05

In [20]:
partner2= partner2.drop(['created_at','updated_at'],axis=1)

In [22]:
partner2

      id partner_type lead_sales_contact created_date updated_date
0      2        Agent             Potato   2020-08-31   2020-12-04
1      3        Agent               Lion   2020-08-31   2021-04-20
2      4        Agent             Potato   2020-08-31   2021-03-25
3      5        Agent               Lion   2020-08-31   2020-12-07
4      6        Agent             Potato   2020-08-31   2021-01-04
..   ...          ...                ...          ...          ...
517  520   Influencer                Sky   2021-05-05   2021-05-05
518  521        Agent                Sky   2021-05-05   2021-05-05
519  522        Agent                Sky   2021-05-05   2021-05-05
520  523        Agent                Sky   2021-05-05   2021-05-05
521  524        Agent                Sky   2021-05-05   2021-05-05

[522 rows x 5 columns]

In [23]:
partner2.to_csv('partnerB.csv',index=False)